# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://createdbypete.com
title: Created by Pete
subtitle: 
author: Peter Rhoades
description:


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
root: 
permalink: /:categories/:title
auto: true
pygments: true

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  compress:
    js:   ~
    css:  ~
  cachebust: none
  gzip: false