# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://www.createdbypete.com
title: Created by Pete
subtitle:
author: Peter Rhoades
description: "Hi, my name is Peter Rhoades and I'm a multidisciplinary design, developer and creator from the UK."
email: hello@createdbypete.com

networks:
  github: createdbypete
  twitter: createdbypete
  googleplus: +PeterRhoades

analytics: true

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
source:      ./source
destination: ./public
root: /
permalink: /:categories/:title/
highlighter: pygments
markdown: redcarpet

# ----------------------- #
#      Jekyll Assets      #
# ----------------------- #
assets:
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  gzip: [  ]
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/assets/fonts
    - _vendor/assets/javascripts
    - _vendor/assets/stylesheets
