# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://createdbypete.com
title: Created by Pete
subtitle: 
author: Peter Rhoades
description:
email: hello@createdbypete.com


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
root: 
permalink: /:categories/:title
pygments: true
exclude: ["vendor","Gemfile","Gemfile.lock","Rakefile"]
markdown: redcarpet
date_format: "ordinal"
titlecase: false

# ----------------------- #
#      Jekyll Assets      #
# ----------------------- #
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  compress:
    js:   uglifier
    css:  sass
  cachebust: hard
  gzip: [ text/css, application/javascript ]