source 'https://rubygems.org'

gem 'middleman', '~> 3.3.0'
gem 'middleman-blog'
gem 'middleman-alias'
gem 'middleman-google-analytics'
gem 'redcarpet'
gem 'nokogiri'
gem 'breakpoint'
gem 'builder', '~> 3.0'
gem 'rqrcode_png'
gem 'middleman-search_engine_sitemap', '~> 1.3.0'
gem 'middleman-syntax'
gem 'middleman-deploy'
