source 'https://rubygems.org'

gem 'middleman', '~> 3.3'
gem 'middleman-blog'
gem 'middleman-alias'
gem 'redcarpet'
gem 'nokogiri'
gem 'compass-normalize'
gem 'breakpoint'
gem 'builder', '~> 3.0'
gem 'rqrcode_png'
gem 'middleman-search_engine_sitemap', path: '../middleman-search_engine_sitemap'
gem 'middleman-syntax'
